/* AI Lifeboard · the free web Lifeboard + the AI coach (BYOK today, built-in app later) */
import { makeTools, TOOL_TABS, LIFETOOLS_CSS, startReminders, affirmationToday } from './lifetools.js';
const SB = { url: 'https://izfccjaznlcffvjxawya.supabase.co', key: 'sb_publishable_b6KPHJ3aPWaxl3yVz93sTw_c47NzfOF' };
const $ = (s, r = document) => r.querySelector(s); const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const toast = (m, ms = 2800) => { const t = document.createElement('div'); t.className = 'toast'; t.textContent = m; document.body.appendChild(t); setTimeout(() => t.remove(), ms); };
const st = document.createElement('style'); st.textContent = LIFETOOLS_CSS; document.head.appendChild(st);
let lb = {}; try { lb = JSON.parse(localStorage.getItem('ailb_board') || '{}') || {}; } catch (e) { } const persist = () => localStorage.setItem('ailb_board', JSON.stringify(lb));
const SKIP = new Set(['halo', 'hugs', 'events']); const tabs = TOOL_TABS.filter(t => !SKIP.has(t[0]));
const main = $('#lb-main'); const nav = $('#lb-nav'); const header = () => `<div class="lb-top"><div class="ava" style="--rc:#6366f1">🤖</div><div><h2>Your Lifeboard</h2><div class="muted2">Saved on this device only. Sign in on allofus.one to sync it to your 3D home.</div></div></div>`;
let R = null; const show = (k) => { nav.querySelectorAll('button').forEach(b => b.classList.toggle('on', b.dataset.t === k)); if (!R) R = makeTools({ main, persist, header, lb, toast, show, celebrate: (e) => toast(e + ' Nice!'), notify: (t, b) => { try { if (Notification.permission === 'granted') new Notification(t, { body: b }); } catch (e) { } }, halo: () => { }, getHalo: () => '', hug: () => toast('🤗 Hugs live in the 3D world: allofus.one'), nearby: () => [], goPlace: () => { location.href = 'https://allofus.one/'; }, me: null, allTabs: () => tabs }); if (R[k]) R[k](); else main.innerHTML = header() + '<p>Coming soon.</p>'; location.hash = k; };
nav.innerHTML = tabs.map(([k, ic, n]) => `<button data-t="${k}">${ic} ${n}</button>`).join(''); nav.onclick = (e) => { const b = e.target.closest('button'); if (b) show(b.dataset.t); }; show(tabs.some(t => t[0] === location.hash.slice(1)) ? location.hash.slice(1) : 'today');
startReminders(() => lb, persist, (t, b) => { try { if (Notification.permission === 'granted') new Notification(t, { body: b }); } catch (e) { } }, toast);

/* ---- the AI coach ---- */
const summary = () => { const g = (lb.goals || []).filter(x => !x.done).slice(0, 5).map(x => x.t || x.title || x.text).filter(Boolean); const top3 = ((lb.top3 && lb.top3.items) || []).filter(Boolean); const rem = (lb.reminders || []).filter(r => !r.done).slice(0, 3).map(r => r.t); const j = (lb.journal || []).slice(-1)[0]; const tr = (lb.metrics || []).map(m => m.name).slice(0, 4); return { date: new Date().toDateString(), affirmation: affirmationToday(lb), top3, goals: g, reminders: rem, lastJournal: j ? String(j.text || j.t || '').slice(0, 240) : '', trackers: tr }; };
const builtIn = (q, S) => { const lq = q.toLowerCase(); const lines = []; if (/plan|today|day|schedule/.test(lq)) { lines.push('Here is a simple plan for ' + S.date + ':'); const items = (S.top3.length ? S.top3 : S.goals.length ? S.goals.slice(0, 3) : ['One thing that moves your biggest goal', 'One thing for your body (walk, water, sleep)', 'One kind thing for someone else']); items.forEach((t, i) => lines.push((i + 1) + '. ' + t + (i === 0 ? '  (do this first, before email)' : ''))); lines.push('Then a 25-minute focus block, a 5-minute break, repeat twice. Stop when it is done, not when you are tired.'); } else if (/goal|stuck|motivat|procrast/.test(lq)) { lines.push('Shrink it. Pick the goal that matters most' + (S.goals[0] ? ' (' + S.goals[0] + ')' : '') + ' and write the smallest next step that takes under 10 minutes. Do that step now, then set a 25-minute Focus timer. Momentum beats motivation every time.'); } else if (/money|budget|debt|save/.test(lq)) { lines.push('Open Money tools: list every bill, then pick one you can cut 10% this month. Put that 10% on the smallest debt or into savings the same day it comes in. Automate it so willpower is not involved.'); } else if (/sad|anx|stress|overwhelm|tired|lonely/.test(lq)) { lines.push('That sounds heavy, and it makes sense you feel it. Try this for 90 seconds: breathe in for 4, hold 4, out for 6, five times. Then write one sentence in the Journal about what is actually in your control today. If this is more than a rough day, please talk to someone you trust or a professional; you deserve that support.'); } else if (/grateful|gratitude|journal/.test(lq)) { lines.push('Write three things: one person, one small thing from today, one thing about yourself. Thirty seconds each. Then read them out loud.'); } else { lines.push('Here is what I see on your board: ' + (S.top3.length ? 'top 3 set (' + S.top3.join(', ') + ')' : 'no top 3 yet') + ', ' + S.goals.length + ' open goals, ' + S.reminders.length + ' reminders coming up.'); lines.push('Ask me to "plan my day", "help me with a goal", "budget", or "I feel stuck". Or add a key below and I will answer anything.'); } lines.push(''); lines.push('Affirmation for today: "' + S.affirmation + '"'); return lines.join('\n'); };
const KEYK = 'ailb_key'; const getKey = () => localStorage.getItem(KEYK) || ''; const chat = $('#ai-chat'); const hist = [];
const bubble = (who, text) => { const d = document.createElement('div'); d.className = 'msg ' + who; d.textContent = text; chat.appendChild(d); chat.scrollTop = chat.scrollHeight; return d; };
const ask = async (q) => { bubble('me', q); const S = summary(); const share = $('#ai-share').checked; const key = getKey(); const thinking = bubble('ai', '…'); hist.push({ role: 'user', content: q });
  if (!key) { await new Promise(r => setTimeout(r, 400)); thinking.textContent = builtIn(q, share ? S : { date: S.date, affirmation: S.affirmation, top3: [], goals: [], reminders: [] }); hist.push({ role: 'assistant', content: thinking.textContent }); return; }
  try { const sys = 'You are the AI Lifeboard coach: warm, direct, practical, a little funny. Short answers (under 160 words) with one concrete next step. Never diagnose; if someone sounds in crisis, gently point them to a trusted person or professional and the 988 line (US). ' + (share ? 'Their Lifeboard today: ' + JSON.stringify(S) : 'They chose not to share their board data.'); const r = await fetch('https://api.anthropic.com/v1/messages', { method: 'POST', headers: { 'content-type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01', 'anthropic-dangerous-direct-browser-access': 'true' }, body: JSON.stringify({ model: 'claude-sonnet-4-5', max_tokens: 400, system: sys, messages: hist.slice(-10) }) }); const j = await r.json(); const t = (j.content || []).map(c => c.text || '').join('') || (j.error && j.error.message) || 'No answer came back.'; thinking.textContent = t; hist.push({ role: 'assistant', content: t }); } catch (e) { thinking.textContent = 'The AI call failed (' + (e.message || e) + '). Check the key, or remove it to use the built-in coach.'; } };
$('#ai-form').onsubmit = (e) => { e.preventDefault(); const q = $('#ai-q').value.trim(); if (!q) return; $('#ai-q').value = ''; ask(q); }; document.querySelectorAll('[data-ask]').forEach(b => b.onclick = () => ask(b.dataset.ask));
const keyUI = () => { $('#ai-keystate').textContent = getKey() ? '🔑 Your key is saved on this device. Claude answers.' : 'No key: the built-in coach answers. Add a Claude API key for full AI.'; }; keyUI();
$('#ai-keysave').onclick = () => { const v = $('#ai-key').value.trim(); if (v) localStorage.setItem(KEYK, v); else localStorage.removeItem(KEYK); $('#ai-key').value = ''; keyUI(); toast(v ? '🔑 Key saved locally.' : 'Key removed.'); };
/* waitlist */
$('#wl-form').onsubmit = async (e) => { e.preventDefault(); const em = $('#wl-e').value.trim(); const err = $('#wl-err'); if (!/^\S+@\S+\.\S+$/.test(em)) { err.textContent = 'Enter a real email.'; return; } if ($('#wl-hp').value) return; try { const r = await fetch(SB.url + '/rest/v1/rpc/submit_lead', { method: 'POST', headers: { 'content-type': 'application/json', apikey: SB.key, authorization: 'Bearer ' + SB.key }, body: JSON.stringify({ p_kind: 'ailifeboard', p_name: $('#wl-n').value.trim() || 'Waitlist', p_business: 'ailifeboard.com', p_email: em, p_phone: '', p_website: location.href, p_details: 'App waitlist' }) }); if (!r.ok) throw new Error('form'); $('#wl-form').innerHTML = '<p class="ok">✅ You are on the list. We will email you when the app opens.</p>'; } catch (e2) { err.innerHTML = 'Our form did not answer. Email <a href="mailto:info@eyetoad.com?subject=AI%20Lifeboard%20waitlist">info@eyetoad.com</a> and we will add you.'; } };
