/* AI Lifeboard · the core Lifeboard tabs, same code as allofus.one (Overview, Goals, Vision, Wellness, Work, Create, Paths) */
export const MODES = {
  home: { label: 'Home', icon: '🏠', color: 0xffd23f, css: '#ffd23f', desc: 'At my place. My I\'M HOME sign is lit. Knock!' },
  hanging: { label: 'Hanging', icon: '🟢', color: 0x7cff6b, css: '#4ade80', desc: 'Open to chat, waves and group hangs.' },
  working: { label: 'Working', icon: '💼', color: 0x38b6ff, css: '#38b6ff', desc: 'Collab invites only. Casual chats wait in a pile.' },
  exploring: { label: 'Exploring', icon: '🧭', color: 0xff8a3d, css: '#ff8a3d', desc: 'Out roaming the paths. Wave hi.' },
  dnd: { label: 'Do Not Disturb', icon: '🌙', color: 0x9aa3b8, css: '#9aa3b8', desc: 'Visible, but not reachable right now.' },
};
export const LIFE_PATHS = [
  { id: 'business', name: 'Business', icon: '💼', color: 0xffd23f, css: '#e0a800', to: 'The City', pts: [[18, -40], [40, -80], [52, -140], [38, -168]] },
  { id: 'learning', name: 'Learning', icon: '📚', color: 0x38b6ff, css: '#2f86ff', to: 'Library of Everything', pts: [[34, -26], [80, -50], [150, -110], [196, -172]] },
  { id: 'wellness', name: 'Wellness', icon: '🌿', color: 0x7cff6b, css: '#22a35a', to: 'The Waterfall', pts: [[-42, -14], [-90, -30], [-160, -40], [-236, -30]] },
  { id: 'adventure', name: 'Adventure', icon: '🏜️', color: 0xff8a3d, css: '#e8671e', to: 'The Desert', pts: [[44, 8], [90, 12], [160, -6], [214, -24]] },
  { id: 'causes', name: 'Causes', icon: '❤️', color: 0xff4f79, css: '#e11d48', to: 'Starport + Orbit Garden', pts: [[38, 24], [76, 40], [160, 92], [206, 186]] },
  { id: 'creativity', name: 'Creativity', icon: '🎨', color: 0xb08cff, css: '#7c3aed', to: 'The Art Garden', pts: [[-30, -34], [-60, -70], [-120, -140], [-160, -180]] },
  { id: 'explore', name: 'Explore', icon: '🌊', color: 0x2fe0c0, css: '#0d9488', to: 'The Beach + Ocean', pts: [[-34, 30], [-70, 70], [-130, 150], [-168, 206]] },
];
const uid = () => 'u' + Math.random().toString(36).slice(2, 9);
export const defaultLB = () => ({ wheel: { Goals: 6, Social: 5, Wellness: 6, Work: 7, Giving: 4, Create: 5 }, goals: [{ id: uid(), t: 'Make my avatar', col: 'done', tag: 'Fun' }, { id: uid(), t: 'Pick my life paths', col: 'doing', tag: 'Me' }, { id: uid(), t: 'Claim my land and build a home', col: 'dream', tag: 'Home' }], vision: { nodes: [{ id: 'n1', x: 40, y: 40, t: '🌍 My why', c: '#7c3aed' }, { id: 'n2', x: 260, y: 120, t: '🎯 First goal', c: '#2563eb' }], links: [['n1', 'n2']] }, habits: [{ id: uid(), t: 'Walk 20 minutes', days: [] }, { id: uid(), t: 'Drink water', days: [] }], moods: [], gratitude: [], projects: [{ id: uid(), t: 'My big idea', s: 'Planning' }], avail: { days: ['Mon', 'Wed', 'Fri'], from: '09:00', to: '17:00' }, feedRules: { who: 'connections', show: ['update', 'win', 'ask', 'offer'] }, links: [], buttons: [{ id: uid(), e: '☀️', l: 'Today', a: 'tab:today' }, { id: uid(), e: '🎯', l: 'Goals', a: 'tab:goals' }, { id: uid(), e: '⏱️', l: 'Focus', a: 'tab:focus' }, { id: uid(), e: '📈', l: 'Trackers', a: 'tab:trackers' }, { id: uid(), e: '💰', l: 'Money', a: 'tab:money' }, { id: uid(), e: '🤝', l: 'Match', a: 'match' }, { id: uid(), e: '🌐', l: 'Worlds', a: 'fx:worlds' }] });
export function makeCore(ctx) { const { main, lb, persist, header, show, esc, $$, $, app, needMe, setMode, closeModal, openMatch, openCollab, today, uid, ago, W, runButton } = ctx; let me = ctx.me; const DB = ctx.DB; const R = {
      overview() { const keys = Object.keys(lb.wheel); const n = keys.length; const cx = 130, cy = 130, r = 112; const cols = ['#7c3aed', '#2563eb', '#16a34a', '#0891b2', '#e11d48', '#ea580c']; const seg = keys.map((k, i) => { const a0 = i / n * Math.PI * 2 - Math.PI / 2, a1 = (i + 1) / n * Math.PI * 2 - Math.PI / 2; const rr = r * lb.wheel[k] / 10; const p = (a, R2) => (cx + Math.cos(a) * R2).toFixed(1) + ',' + (cy + Math.sin(a) * R2).toFixed(1); const am = (a0 + a1) / 2; return `<path d="M${cx},${cy} L${p(a0, r)} A${r},${r} 0 0 1 ${p(a1, r)} Z" fill="${cols[i]}" opacity=".12"/><path class="seg" data-k="${k}" d="M${cx},${cy} L${p(a0, rr)} A${rr},${rr} 0 0 1 ${p(a1, rr)} Z" fill="${cols[i]}" opacity=".85"/><text x="${(cx + Math.cos(am) * (r + 14)).toFixed(0)}" y="${(cy + Math.sin(am) * (r + 14) + 4).toFixed(0)}" text-anchor="middle" font-size="11" font-weight="700" fill="#0f172a">${k}</text>`; }).join('');
        const done = lb.goals.filter(g => g.col === 'done').length;
        main.innerHTML = header() + `<div class="lb-btns">${lb.buttons.map(b => `<button class="aou-btn" data-btn="${b.id}">${esc(b.e)} ${esc(b.l)}</button>`).join('')}<button class="aou-btn ghost" data-go="buttons">＋ Add button</button></div><div class="lb-two"><div class="lb-card"><h3>Life balance wheel</h3><svg viewBox="-20 -20 300 300" class="wheel">${seg}<circle cx="${cx}" cy="${cy}" r="18" fill="#fff" stroke="#e2e8f0"/></svg><p class="muted2">Slide to rate each part of your life from 1 to 10. Tap a slice to open it.</p>${keys.map(k => `<label class="sl">${k}<input type="range" min="1" max="10" value="${lb.wheel[k]}" data-w="${k}"><b>${lb.wheel[k]}</b></label>`).join('')}</div><div class="lb-card"><h3>Today</h3><p>🎯 <b>${lb.goals.filter(g => g.col === 'doing').length}</b> goals in progress · ✅ <b>${done}</b> done</p><p>🌿 Habits checked today: <b>${lb.habits.filter(h => h.days.includes(today())).length}/${lb.habits.length}</b></p><p>✨ Light Seeds found: <b>${W.seedCount()}/7</b></p><p class="muted2">${W.seedHints()}</p><div class="aou-row"><button class="aou-btn" data-go="goals">Open goals</button><button class="aou-btn" data-go="wellness">Check in</button></div></div></div>`;
        $$('input[data-w]', main).forEach(i => i.oninput = () => { lb.wheel[i.dataset.w] = +i.value; persist(); R.overview(); });
        $$('.seg', main).forEach(s => s.onclick = () => show({ Goals: 'goals', Social: 'social', Wellness: 'wellness', Work: 'work', Giving: 'giving', Create: 'create' }[s.dataset.k] || 'overview'));
        $$('[data-btn]', main).forEach(b => b.onclick = () => runButton(lb.buttons.find(x => x.id === b.dataset.btn))); },
      goals() { const cols = [['dream', '💭 Dreaming'], ['doing', '🔨 Doing'], ['done', '✅ Done']]; main.innerHTML = header() + `<div class="lb-card"><h3>Goal stacker</h3><p class="muted2">Drag goals between columns and up or down to stack them by priority. On a phone, use the arrows.</p><div class="aou-compose"><input id="g-new" maxlength="90" placeholder="New goal…"><select id="g-tag"><option>Me</option><option>Work</option><option>Health</option><option>Money</option><option>People</option><option>Giving</option><option>Fun</option><option>Home</option></select><button class="aou-btn primary" id="g-add">Add</button></div><div class="stack">${cols.map(([c, n]) => `<div class="col" data-col="${c}"><h4>${n} <small>${lb.goals.filter(g => g.col === c).length}</small></h4>${lb.goals.filter(g => g.col === c).map(g => `<div class="gcard" draggable="true" data-id="${g.id}"><span>${esc(g.t)}</span><small class="tag">${esc(g.tag || '')}</small><div class="gbtn"><button data-mv="up" title="Higher">▲</button><button data-mv="down" title="Lower">▼</button><button data-mv="left" title="Back">◀</button><button data-mv="right" title="Forward">▶</button><button data-mv="del" title="Delete">✕</button></div></div>`).join('')}</div>`).join('')}</div></div>`;
        $('#g-add', main).onclick = () => { const t = $('#g-new', main).value.trim(); if (!t) return; lb.goals.push({ id: uid(), t, col: 'dream', tag: $('#g-tag', main).value }); persist(); R.goals(); };
        let drag = null; $$('.gcard', main).forEach(c => { c.ondragstart = () => { drag = c.dataset.id; c.classList.add('drag'); }; c.ondragend = () => c.classList.remove('drag'); });
        $$('.col', main).forEach(col => { col.ondragover = (e) => e.preventDefault(); col.ondrop = (e) => { e.preventDefault(); if (!drag) return; const g = lb.goals.find(x => x.id === drag); const over = e.target.closest('.gcard'); lb.goals = lb.goals.filter(x => x !== g); g.col = col.dataset.col; if (over && over.dataset.id !== drag) { const i = lb.goals.findIndex(x => x.id === over.dataset.id); lb.goals.splice(i, 0, g); } else lb.goals.push(g); if (g.col === 'done') app.celebrate('🎯'); persist(); R.goals(); }; });
        main.querySelector('.stack').onclick = (e) => { const b = e.target.closest('[data-mv]'); if (!b) return; const id = b.closest('.gcard').dataset.id; const i = lb.goals.findIndex(x => x.id === id); const g = lb.goals[i]; const order = ['dream', 'doing', 'done']; const mv = b.dataset.mv; if (mv === 'del') lb.goals.splice(i, 1); else if (mv === 'left' || mv === 'right') { const k = order.indexOf(g.col) + (mv === 'right' ? 1 : -1); if (k >= 0 && k < 3) { g.col = order[k]; if (g.col === 'done') app.celebrate('🎯'); } } else { const same = lb.goals.map((x, j) => [x, j]).filter(([x]) => x.col === g.col); const p = same.findIndex(([x]) => x === g); const o = same[p + (mv === 'up' ? -1 : 1)]; if (o) { [lb.goals[i], lb.goals[o[1]]] = [lb.goals[o[1]], lb.goals[i]]; } } persist(); R.goals(); }; },
      vision() { const V = lb.vision; main.innerHTML = header() + `<div class="lb-card"><h3>Vision board</h3><p class="muted2">Add ideas, drag them anywhere, and link them into a flowchart: tap 🔗 Link, then two cards.</p><div class="aou-compose"><input id="v-new" maxlength="60" placeholder="🌱 An idea, a dream, a step…"><input id="v-col" type="color" value="#2563eb"><button class="aou-btn primary" id="v-add">Add</button><button class="aou-btn" id="v-link">🔗 Link</button></div><div class="vboard" id="vb"><svg id="vl"></svg>${V.nodes.map(n => `<div class="vnode" data-id="${n.id}" style="left:${n.x}px;top:${n.y}px;--c:${n.c}"><span>${esc(n.t)}</span><button data-del="${n.id}">✕</button></div>`).join('')}</div></div>`;
        const vb = $('#vb', main), svg = $('#vl', main); const lines = () => { svg.setAttribute('width', vb.scrollWidth); svg.setAttribute('height', vb.scrollHeight); svg.innerHTML = '<defs><marker id="ah" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#64748b"/></marker></defs>' + V.links.map(([a, b]) => { const A = vb.querySelector(`[data-id="${a}"]`), B = vb.querySelector(`[data-id="${b}"]`); if (!A || !B) return ''; const ax = A.offsetLeft + A.offsetWidth / 2, ay = A.offsetTop + A.offsetHeight / 2, bx = B.offsetLeft + B.offsetWidth / 2, by = B.offsetTop + B.offsetHeight / 2; return `<path d="M${ax},${ay} C${(ax + bx) / 2},${ay} ${(ax + bx) / 2},${by} ${bx},${by}" stroke="#64748b" stroke-width="2.5" fill="none" marker-end="url(#ah)"/>`; }).join(''); }; requestAnimationFrame(lines);
        let linkA = null, linking = false; $('#v-link', main).onclick = (e) => { linking = !linking; linkA = null; e.target.classList.toggle('primary', linking); };
        $('#v-add', main).onclick = () => { const t = $('#v-new', main).value.trim(); if (!t) return; V.nodes.push({ id: uid(), x: 30 + Math.random() * 200, y: 30 + Math.random() * 160, t, c: $('#v-col', main).value }); persist(); R.vision(); };
        $$('.vnode', vb).forEach(el => { let sx, sy, ox, oy, moved = false; el.onpointerdown = (e) => { if (e.target.dataset.del) return; el.setPointerCapture(e.pointerId); sx = e.clientX; sy = e.clientY; ox = el.offsetLeft; oy = el.offsetTop; moved = false; el.onpointermove = (ev) => { const dx = ev.clientX - sx, dy = ev.clientY - sy; if (Math.abs(dx) + Math.abs(dy) > 4) moved = true; el.style.left = Math.max(0, ox + dx) + 'px'; el.style.top = Math.max(0, oy + dy) + 'px'; lines(); }; }; el.onpointerup = () => { el.onpointermove = null; const n = V.nodes.find(q => q.id === el.dataset.id); n.x = el.offsetLeft; n.y = el.offsetTop; persist(); if (!moved && linking) { if (!linkA) { linkA = n.id; el.classList.add('sel'); } else if (linkA !== n.id) { V.links.push([linkA, n.id]); linkA = null; persist(); R.vision(); } } }; });
        vb.onclick = (e) => { const d = e.target.dataset.del; if (!d) return; V.nodes = V.nodes.filter(n => n.id !== d); V.links = V.links.filter(l => l[0] !== d && l[1] !== d); persist(); R.vision(); }; },
      wellness() { const d = today(); const last7 = [...Array(7)].map((_, i) => new Date(Date.now() - (6 - i) * 86400000).toISOString().slice(0, 10)); const moods = ['😞', '😕', '😐', '🙂', '😄'];
        main.innerHTML = header() + `<div class="lb-two"><div class="lb-card"><h3>Habits</h3>${lb.habits.map(h => { const streak = (() => { let s = 0; for (let i = 0; i < 365; i++) { const k = new Date(Date.now() - i * 86400000).toISOString().slice(0, 10); if (h.days.includes(k)) s++; else if (i > 0) break; } return s; })(); return `<div class="habit"><label><input type="checkbox" data-h="${h.id}" ${h.days.includes(d) ? 'checked' : ''}> ${esc(h.t)}</label><span class="days">${last7.map(k => `<i class="${h.days.includes(k) ? 'on' : ''}"></i>`).join('')}</span><small>🔥 ${streak}</small><button class="x" data-hd="${h.id}">✕</button></div>`; }).join('')}<div class="aou-compose"><input id="h-new" maxlength="50" placeholder="New habit…"><button class="aou-btn primary" id="h-add">Add</button></div></div>
          <div class="lb-card"><h3>How are you today?</h3><div class="moods">${moods.map((e, i) => `<button data-m="${i}" class="${(lb.moods.find(x => x.d === d) || {}).v === i ? 'on' : ''}">${e}</button>`).join('')}</div><p class="muted2">Last 7 days: ${last7.map(k => { const x = lb.moods.find(q => q.d === k); return x ? moods[x.v] : '·'; }).join(' ')}</p><h3>Grateful for</h3><div class="aou-compose"><input id="gr-t" maxlength="120" placeholder="One good thing…"><button class="aou-btn primary" id="gr-go">Save</button></div>${lb.gratitude.slice(-5).reverse().map(g => `<p>🙏 ${esc(g.t)} <small class="muted2">${g.d}</small></p>`).join('')}<p class="muted2">Hard day? You are not alone. In the US call or text <b>988</b>. Elsewhere, see <a href="https://findahelpline.com/" target="_blank" rel="noopener">findahelpline.com</a>.</p></div></div>`;
        $$('[data-h]', main).forEach(c => c.onchange = () => { const h = lb.habits.find(x => x.id === c.dataset.h); h.days = c.checked ? [...new Set([...h.days, d])] : h.days.filter(x => x !== d); persist(); R.wellness(); }); $$('[data-hd]', main).forEach(b => b.onclick = () => { lb.habits = lb.habits.filter(h => h.id !== b.dataset.hd); persist(); R.wellness(); });
        $('#h-add', main).onclick = () => { const t = $('#h-new', main).value.trim(); if (!t) return; lb.habits.push({ id: uid(), t, days: [] }); persist(); R.wellness(); }; $$('.moods button', main).forEach(b => b.onclick = () => { lb.moods = lb.moods.filter(x => x.d !== d); lb.moods.push({ d, v: +b.dataset.m }); persist(); R.wellness(); }); $('#gr-go', main).onclick = () => { const t = $('#gr-t', main).value.trim(); if (!t) return; lb.gratitude.push({ t, d }); persist(); R.wellness(); }; },
      work() { const A = lb.avail; const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']; const mt = DB.meetings(); const link = location.origin + '/?book=' + encodeURIComponent((me && me.username) || 'you');
        main.innerHTML = header() + `<div class="lb-two"><div class="lb-card"><h3>Projects</h3>${lb.projects.map(p => `<div class="habit"><b>${esc(p.t)}</b><select data-ps="${p.id}">${['Idea', 'Planning', 'Building', 'Launched', 'Paused'].map(s => `<option ${p.s === s ? 'selected' : ''}>${s}</option>`).join('')}</select><button class="x" data-pd="${p.id}">✕</button></div>`).join('')}<div class="aou-compose"><input id="pj-t" maxlength="60" placeholder="New project…"><button class="aou-btn primary" id="pj-add">Add</button></div><h3>Collab</h3><p class="muted2">Switch to 💼 Working mode and open a collab room in the City.</p><div class="aou-row"><button class="aou-btn" id="wk-mode">💼 Go to Working mode</button><button class="aou-btn" id="wk-room">🧑‍💻 Collab rooms</button></div></div>
          <div class="lb-card"><h3>Calendar + booking</h3><p class="aou-lbl">I take meetings on</p><div class="aou-chips" id="av-d">${days.map(d => `<button data-v="${d}" class="${A.days.includes(d) ? 'on' : ''}">${d}</button>`).join('')}</div><div class="aou-grid2"><label>From<input type="time" id="av-f" value="${A.from}"></label><label>To<input type="time" id="av-t" value="${A.to}"></label></div><p class="aou-lbl">My booking link</p><div class="aou-compose"><input readonly value="${esc(link)}"><button class="aou-btn" id="bk-copy">Copy</button></div><h3>Requests I sent</h3>${mt.map(x => `<p>${{ call: '📞', meeting: '💼', vr: '🥽' }[x.kind] || '📅'} ${esc(x.toName)} · ${esc((x.when || '').replace('T', ' '))} <span class="aou-tag">${esc(x.status)}</span></p>`).join('') || '<p class="muted2">None yet. Tap anyone and choose 📅 Request a meeting.</p>'}</div></div>`;
        $('#pj-add', main).onclick = () => { const t = $('#pj-t', main).value.trim(); if (!t) return; lb.projects.push({ id: uid(), t, s: 'Idea' }); persist(); R.work(); }; $$('[data-ps]', main).forEach(s => s.onchange = () => { lb.projects.find(p => p.id === s.dataset.ps).s = s.value; persist(); }); $$('[data-pd]', main).forEach(b => b.onclick = () => { lb.projects = lb.projects.filter(p => p.id !== b.dataset.pd); persist(); R.work(); });
        $$('#av-d button', main).forEach(b => b.onclick = () => { const v = b.dataset.v; A.days = A.days.includes(v) ? A.days.filter(x => x !== v) : [...A.days, v]; persist(); R.work(); }); $('#av-f', main).onchange = (e) => { A.from = e.target.value; persist(); }; $('#av-t', main).onchange = (e) => { A.to = e.target.value; persist(); };
        $('#bk-copy', main).onclick = () => { navigator.clipboard && navigator.clipboard.writeText(link); app.toast('📋 Booking link copied'); }; $('#wk-mode', main).onclick = () => { setMode('working'); app.toast('💼 Working mode on'); }; $('#wk-room', main).onclick = () => openCollab(); },
      create() { main.innerHTML = header() + `<div class="lb-card"><h3>My music, art and work</h3><p class="muted2">Link your songs, art, videos, shop or portfolio. They show on your card and in your home.</p><div class="aou-compose"><input id="ln-t" maxlength="50" placeholder="Title"><input id="ln-u" maxlength="300" placeholder="https://…"><button class="aou-btn primary" id="ln-add">Add</button></div><div class="links">${lb.links.map(l => `<div class="aou-li"><a href="${esc(l.u)}" target="_blank" rel="noopener"><b>${esc(l.t)}</b><small>${esc(l.u)}</small></a><button class="x" data-ld="${l.id}">✕</button></div>`).join('') || '<p class="muted2">Nothing linked yet.</p>'}</div><h3>Song that plays at my home</h3><div class="aou-compose"><input id="sg-u" placeholder="YouTube link" value="${esc((me && me.home && me.home.song) || '')}"><button class="aou-btn" id="sg-go">Save</button></div></div>`;
        $('#ln-add', main).onclick = () => { const t = $('#ln-t', main).value.trim(), u = $('#ln-u', main).value.trim(); if (!t || !/^https?:\/\//i.test(u)) { app.toast('Add a title and a full https:// link'); return; } lb.links.push({ id: uid(), t, u }); persist(); R.create(); }; main.querySelector('.links').onclick = (e) => { const d = e.target.dataset.ld; if (d) { lb.links = lb.links.filter(l => l.id !== d); persist(); R.create(); } }; $('#sg-go', main).onclick = async () => { if (!needMe('Join to set your home song.')) return; me.home = Object.assign(me.home || {}, { song: $('#sg-u', main).value.trim() }); await DB.saveMe(me); app.toast('🎵 Saved'); }; },
      paths() { const mine = (me && me.paths) || []; main.innerHTML = header() + `<div class="lb-card"><h3>My life paths</h3><p class="muted2">Your avatar stands on your first path so people walking it can find you. Pick as many as fit.</p><div class="pathgrid">${LIFE_PATHS.map(p => `<button data-p="${p.id}" class="${mine.includes(p.id) ? 'on' : ''}" style="--c:${p.css}"><span>${p.icon}</span><b>${p.name}</b><small>→ ${esc(p.to)}</small></button>`).join('')}</div><div class="aou-row"><button class="aou-btn" id="pt-go">🚶 Walk my path</button></div></div>`; $$('.pathgrid button', main).forEach(b => b.onclick = async () => { if (!needMe('Join to choose your paths.')) return; const v = b.dataset.p; me.paths = mine.includes(v) ? mine.filter(x => x !== v) : [...mine, v]; await DB.saveMe(me); R.paths(); }); $('#pt-go', main).onclick = () => { const id = (mine[0] || 'wellness'); closeModal(); app.travel('path-' + id); }; },
  }; return R; }
